export const GET_ANGGARAN = "GET_ANGGARAN";
export const RECEIVE_ANGGARAN = "RECEIVE_ANGGARAN";
export const GET_ANGGARAN_HEADER = "GET_ANGGARAN_HEADER";
export const RECEIVE_ANGGARAN_HEADER = "RECEIVE_ANGGARAN_HEADER";
export const GET_ANGGARAN_REQUESTED = "GET_ANGGARAN_REQUESTED";
export const GET_ANGGARAN_HEADER_REQUESTED = "GET_ANGGARAN_HEADER_REQUESTED";
